
parameters:
  _param:
    salt_control_trusty_image: http://apt.tcpcloud.eu/images/ubuntu-14-04-x64-201612140957.qcow2
    salt_control_xenial_image: http://apt.tcpcloud.eu/images/ubuntu-16-04-x64-201612140953.qcow2
    salt_api_password_hash: "$6$TqtkKU7o$dKPPRedy/WPPuSWvi7XiR4QqzgMsmr2eW5c.DR71yO0Mqh4X6iPwc.QvqfDgK0wtjaxCboAXkxYeV1NVVDY2a0"
  linux:
    network:
      host:
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - ${_param:infra_config_hostname}
          - ${_param:infra_config_hostname}.${_param:cluster_domain}
        cfg:
          address: ${_param:infra_config_address}
          names:
          - cfg
          - cfg.${_param:cluster_domain}
    system:
      name: ${_param:infra_config_hostname}
      domain: ${_param:cluster_domain}