classes:
- system.linux.system.repo.docker
- system.kubernetes.pool.single
- system.salt.minion.cert.k8s_client_single
#- system.bird.server.single
- cluster.k8s-salt-model
parameters:
  kubernetes:
    pool:

#        volumes:
#          - /srv/calico/bird.cfg.mesh.template:/etc/calico/confd/templates/bird.cfg.mesh.template
#          - /srv/calico/bird.cfg.no-mesh.template:/etc/calico/confd/templates/bird.cfg.no-mesh.template
#          - /srv/calico/custom_filters.cfg:/etc/calico/confd/config/custom_filters.cfg
      network:
        engine: opencontrail
        opencontrail:
          address: ${_param:kubernetes_control_node01_address}
    common:
      hyperkube:
        image: tcpcloud/hyperkube:v1.5.1
##FIXME
 # linux:
 #   network:
 #     interface:
 #       eth0:
 #         enabled: true
 #         type: slave
 #         master: bond1
 #         mtu: 9000
 #         pre_up_cmds:
 #         - /sbin/ethtool --offload eth6 rx off tx off tso off gro off
 #       eth1:
 #         enabled: true
 #         type: slave
 #         master: bond1
 #         mtu: 9000
 #         pre_up_cmds:
 #         - /sbin/ethtool --offload eth7 rx off tx off tso off gro off
 #       bond0:
 #         enabled: true
 #         proto: manual
 #         type: bond
 #         use_interfaces:
 #         - eth0
 #         - eth1
 #         slaves: eth0 eth1
 #         mode: active-backup
 #         mtu: 9000
