
parameters:
  _param:
    kubernetes_admin_user: admin
    kubernetes_admin_password: WWWWWWWWWWWWWWWW
    kubernetes_admin_token: WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
    kubernetes_kubelet_token: WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
    kubernetes_kube-proxy_token: WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
    kubernetes_scheduler_token: WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
    kubernetes_controller-manager_token: WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
    kubernetes_dns_token: WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
    etcd_initial_token: WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
    kubernetes_internal_api_address: 10.254.0.1
    node_address: ${_param:single_address}
    node_hostname: ${_param:kubernetes_control_node01_hostname}
    node_port: 4001
  linux:
    network:
      host:
        ctl01:
          address: ${_param:kubernetes_control_node01_address}
          names:
          - ${_param:kubernetes_control_node01_hostname}
          - ${_param:kubernetes_control_node01_hostname}.${_param:cluster_domain}
        cmp01:
          address: ${_param:kubernetes_compute_node01_single_address}
          names:
          - ${_param:kubernetes_compute_node01_hostname}
          - ${_param:kubernetes_compute_node01_hostname}.${_param:cluster_domain}
        cmp02:
          address: ${_param:kubernetes_compute_node02_single_address}
          names:
          - ${_param:kubernetes_compute_node02_hostname}
          - ${_param:kubernetes_compute_node02_hostname}.${_param:cluster_domain}
      resolv:
        dns:
          - 10.254.0.10
          - 8.8.8.8
        domain: k8s-oc.local
        search:
          - bud.mirantis.net 
          - scc.mirantis.net 
          - vm.mirantis.net 
          - ssl.mirantis.net 
          - msk.mirantis.net 
          - srt.mirantis.net
        options:
          - ndots:5
          - timeout:2
          - attempts:2
